import * as THREE from 'three';
import { defaultGravity } from './constants.js';
import { maxHp } from '../data/balance.js';

export function createGameState() {
  const drag = {
    active: false,
    x: 0,
    targetRotation: 0,
  };

  const touchPointerIds = new Set();

  return {
    ballVelocity: 0,
    gravity: defaultGravity,
    terminalVelocity: 28,
    stompImpulse: 5.4,
    cannonChargeTime: 3,
    cannonCooldown: 5,
    laserRingOnTime: 2,
    laserRingOffTime: 2,
    bounceVelocity: 7.7,
    score: 0,
    currentLevel: 1,
    platformsPassedThisLevel: 0,
    nextPlatformId: 0,
    isGameOver: false,
    isPaused: false,
    impulseMode: 'A',
    impulseBResetSpeed: defaultGravity * 0.1,
    impulseBShotgunImpulse: 4,
    controlMode: 'A',
    twistBMode: false,
    timeScale: 1,
    damageSlowdownTimer: 0,
    grayscaleAmount: 0,
    coinAttractionRadius: 1.05,
    playerHitboxScale: 0.3,
    hp: maxHp,
    coins: 0,
    damageCooldown: 0,
    acidStompImmunity: 0,
    acidBurnCooldown: 0,
    damageFlashTimer: 0,
    pendingInvulnerability: false,
    pendingShield: false,
    invulnerabilityTimer: 0,
    hasShield: false,
    rewardChosen: false,
    maxAmmo: 5,
    fireInterval: 0.3,
    shotgunFireInterval: 0.7,
    shotgunSpreadAngle: 5,
    bulletImpulse: 4.3,
    ammo: 5,
    isShooting: false,
    fireCooldown: 0,
    combo: 0,
    comboSprite: null,
    comboTexture: null,
    comboMaterial: null,
    selectedWeapon: 'machinegun',
    nextShotId: 1,
    scaledTime: 0,
    piercingBulletsUnlocked: false,
    vampiricLifeUnlocked: false,
    comboShieldUnlocked: false,
    vampiricKillCount: 0,
    comboShieldAwardedThisCombo: false,
    shopTilePlat: null,
    shopTileRef: null,
    shopUsed: false,
    isLevelComplete: false,
    shakeIntensity: 0,
    shakeDecay: 0,
    shakeOffset: new THREE.Vector3(),
    cameraBasePos: new THREE.Vector3(),
    drag,
    touchPointerIds,
    platforms: [],
    bullets: [],
    enemies: [],
    particles: [],
    floatingTexts: [],
    crates: [],
    goldBlocks: [],
    coinPickups: [],
    cannons: [],
    shockwaves: [],
    pillarLaserRings: [],
    bounceCubes: [],
    pillarSpikes: [],
    spikeTraps: [],
    sawBlades: [],
    floaters: [],
    acidPuddles: [],
    nextBounceCubeOrder: 1,
    spikePlatformsThisLevel: 0,
    groundWormsSinceTurtle: 0,
    acidSnailsThisLevel: 0,
    scoreSubmittedToLeaderboard: false,
    leaderboardPendingClose: false,
    gameOverScreenShown: false,
  };
}
